#!/bin/bash

binary='https://circleci.com/api/v1/project/agustinmista/mdviewer/latest/artifacts/0/%24CIRCLE_ARTIFACTS/build/mdviewer?filter=successful&amp;branch=master'

data='https://github.com/agustinmista/mdviewer/trunk/data'


if ! type wget &> /dev/null; then
    echo "cannot find wget on the \$PATH, it is installed?"
fi

if ! type svn &> /dev/null ; then
    echo "cannot find svn on the \$PATH, it is installed?"
fi

# Retrieve the artifact generated by CircleCI
wget $binary -O ~/.local/bin/mdviewer
chmod +x ~/.local/bin/mdviewer

# Retrieve the data files from github subfolder
svn export $data ~/.local/share/mdviewer --force 
